# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/proto/decompile_update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#server/proto/decompile_update.proto\"#\n\x0f\x44\x65\x63ompileUpdate\x12\x10\n\x08\x66ilename\x18\x01 \x01(\tb\x06proto3')



_DECOMPILEUPDATE = DESCRIPTOR.message_types_by_name['DecompileUpdate']
DecompileUpdate = _reflection.GeneratedProtocolMessageType('DecompileUpdate', (_message.Message,), {
  'DESCRIPTOR' : _DECOMPILEUPDATE,
  '__module__' : 'server.proto.decompile_update_pb2'
  # @@protoc_insertion_point(class_scope:DecompileUpdate)
  })
_sym_db.RegisterMessage(DecompileUpdate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DECOMPILEUPDATE._serialized_start=39
  _DECOMPILEUPDATE._serialized_end=74
# @@protoc_insertion_point(module_scope)
