# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/proto/decompiler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.proto import decompile_result_pb2 as server_dot_proto_dot_decompile__result__pb2
from server.proto import decompile_request_pb2 as server_dot_proto_dot_decompile__request__pb2
from server.proto import decompile_update_pb2 as server_dot_proto_dot_decompile__update__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dserver/proto/decompiler.proto\x1a#server/proto/decompile_result.proto\x1a$server/proto/decompile_request.proto\x1a#server/proto/decompile_update.proto\"\x1f\n\x0bPingMessage\x12\x10\n\x08sequence\x18\x01 \x01(\x05\"\x1f\n\x0bPongMessage\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x32\x94\x01\n\nDecompiler\x12\x34\n\tDecompile\x12\x11.DecompileRequest\x1a\x10.DecompileResult\"\x00\x30\x01\x12,\n\x06Update\x12\x10.DecompileUpdate\x1a\x10.DecompileResult\x12\"\n\x04Ping\x12\x0c.PingMessage\x1a\x0c.PongMessageb\x06proto3')



_PINGMESSAGE = DESCRIPTOR.message_types_by_name['PingMessage']
_PONGMESSAGE = DESCRIPTOR.message_types_by_name['PongMessage']
PingMessage = _reflection.GeneratedProtocolMessageType('PingMessage', (_message.Message,), {
  'DESCRIPTOR' : _PINGMESSAGE,
  '__module__' : 'server.proto.decompiler_pb2'
  # @@protoc_insertion_point(class_scope:PingMessage)
  })
_sym_db.RegisterMessage(PingMessage)

PongMessage = _reflection.GeneratedProtocolMessageType('PongMessage', (_message.Message,), {
  'DESCRIPTOR' : _PONGMESSAGE,
  '__module__' : 'server.proto.decompiler_pb2'
  # @@protoc_insertion_point(class_scope:PongMessage)
  })
_sym_db.RegisterMessage(PongMessage)

_DECOMPILER = DESCRIPTOR.services_by_name['Decompiler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGMESSAGE._serialized_start=145
  _PINGMESSAGE._serialized_end=176
  _PONGMESSAGE._serialized_start=178
  _PONGMESSAGE._serialized_end=209
  _DECOMPILER._serialized_start=212
  _DECOMPILER._serialized_end=360
# @@protoc_insertion_point(module_scope)
